import { useState } from 'react';
import { getAllProducts, getCategories, getIssues, getGeneralIssues, addProduct } from '../data/store.js';
const fields = [['speed','Velocidad'],['motor','Motor'],['capacity','Capacidad'],['area','Área'],['weight','Peso'],['folded','Plegado'],['control','Control'],['assembly','Ensamblaje'],['notes','Notas']];
export default function Catalog({ notify }) {
  const [products, setProducts] = useState(getAllProducts);
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('All');
  const [expanded, setExpanded] = useState(null); const [adding, setAdding] = useState(false);
  const [form, setForm] = useState({ cat: 'Vertical Fold', name: '', model: '', capacity: '', links: [], notes: '' });
  const filtered = products.filter(p => (category === 'All' || p.cat === category) && [p.name,p.model,p.speed,p.motor,p.notes,p.cat,p.capacity,...getIssues(p.issueKey).flatMap(i=>[i.code,i.name,i.fix])].some(v => String(v||'').toLowerCase().includes(query.toLowerCase().trim())));
  function save(e) { e.preventDefault(); if (!form.name.trim() || !form.model.trim() || !form.capacity.trim()) { notify('Nombre, modelo y capacidad son obligatorios.'); return; }
    if (form.links.some(link => link.url && !/^https?:\/\//i.test(link.url))) { notify('Los enlaces deben comenzar con http:// o https://.'); return; }
    const links = form.links.filter(link => link.url).map(link => ({ ...link, label: link.label || 'Enlace' }));
    const product = { ...form, links, id: `custom_${Date.now()}_${Math.random().toString(36).slice(2)}`, isCustom: true, issueKey: '' };
    if (!addProduct(product)) { notify('No se pudo guardar. Conservamos el formulario para reintentar.'); return; }
    setProducts(getAllProducts()); setAdding(false); notify('Producto guardado.'); setForm({ cat: 'Vertical Fold', name: '', model: '', capacity: '', links: [], notes: '' }); }
  return <><div className="controls"><input aria-label="Buscar catálogo" placeholder="Buscar modelo, error, síntoma..." value={query} onChange={e=>setQuery(e.target.value)} /> <button onClick={()=>setAdding(true)}>+ Producto</button><span>{filtered.length} productos</span><div className="tabs">{getCategories().map(c=><button key={c.key} className={category===c.key?'active':''} onClick={()=>setCategory(c.key)}>{c.label}</button>)}</div></div>
    <div className="grid">{filtered.map((p,i)=><article className="card" key={p.id || `${p.model}-${i}`}><button className="card-title" onClick={()=>setExpanded(expanded===p?null:p)} aria-expanded={expanded===p}><strong>{p.name}</strong> <span>{p.model}</span></button><small>{p.cat}{p.isCustom?' · Local':''}</small><p>{p.speed} · {p.capacity}</p>{expanded===p&&<div className="detail"><div className="spec-grid">{fields.filter(([k])=>p[k]&&p[k]!=='—').map(([k,label])=><div key={k}><small>{label}</small><div>{p[k]}</div></div>)}</div><h3>Errores conocidos</h3>{getIssues(p.issueKey).length?getIssues(p.issueKey).map(iss=><details key={iss.id}><summary><b>{iss.code}</b> {iss.name}</summary><p className="preline">{iss.fix}</p>{iss.parts&&<p>Repuestos: {iss.parts}</p>}</details>):<p>Sin errores específicos registrados.</p>}{p.links?.map((link,j)=><a key={j} href={/^https?:\/\//i.test(link.url)?link.url:undefined} target="_blank" rel="noreferrer">{link.label || link.url}</a>)}</div>}</article>)}</div>
    {!filtered.length&&<p>Sin resultados.</p>}{!query&&<section><h2>Problemas generales</h2><div className="grid">{getGeneralIssues().map((issue,i)=><details className="card" key={i}><summary>{issue.code} · {issue.name}</summary><p>{issue.fix}</p></details>)}</div></section>}
    {adding&&<div className="overlay"><form className="panel" onSubmit={save}><div className="panel-head"><h2>Nuevo producto</h2><button type="button" onClick={()=>setAdding(false)}>Cerrar</button></div><label>Nombre<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Modelo<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label><label>Categoría<select value={form.cat} onChange={e=>setForm({...form,cat:e.target.value})}>{getCategories().filter(c=>c.key!=='All').map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select></label>{fields.map(([key,label])=><label key={key}>{label}<input value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<h3>Enlaces y precios</h3>{form.links.map((link,index)=><div className="link-row" key={index}><input aria-label={`Tienda ${index+1}`} placeholder="Tienda" value={link.label} onChange={e=>setForm({...form,links:form.links.map((x,i)=>i===index?{...x,label:e.target.value}:x)})}/><input aria-label={`URL ${index+1}`} placeholder="https://..." value={link.url} onChange={e=>setForm({...form,links:form.links.map((x,i)=>i===index?{...x,url:e.target.value}:x)})}/><input aria-label={`Precio ${index+1}`} placeholder="Precio" value={link.price} onChange={e=>setForm({...form,links:form.links.map((x,i)=>i===index?{...x,price:e.target.value}:x)})}/><button type="button" onClick={()=>setForm({...form,links:form.links.filter((_,i)=>i!==index)})}>Quitar</button></div>)}<button type="button" onClick={()=>setForm({...form,links:[...form.links,{label:'',url:'',price:''}]})}>+ Enlace</button><p>Los precios se introducen manualmente. Consultarlos en una tienda requiere Internet.</p><button>Guardar producto</button></form></div>}</>;
}
